name: C tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make zlib1g-dev  meson
    - name: Build and install nthash from source
      run: |
        git clone https://github.com/bcgsc/ntHash.git
        cd ntHash
        sed -i '1i#include <cstdint>' /ntHash/src/internal.hpp
        meson setup --buildtype=release build
        meson install -C build 
        # Verify installation
        ls -la /usr/local/lib/libnthash*
        ls -la /usr/local/include/nthash/
    - name: Build project
      run: make

