name: Compile check

on:
  push:
    branches: ["main", "dev"]
    paths:
      - 'csyncmer_fast.h'
      - 'example.c'
  pull_request:
    branches: ["main", "dev"]
    paths:
      - 'csyncmer_fast.h'
      - 'example.c'
  workflow_dispatch:


jobs:
  build_example:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        native: [true, false]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install gcc (Windows)
      if: runner.os == 'Windows'
      run: choco install mingw -y

    - name: Build example (Unix)
      if: runner.os != 'Windows'
      run: cc -std=c11 -O3 ${{ matrix.native && '-march=native' || '' }} -o example example.c

    - name: Build example (Windows)
      if: runner.os == 'Windows'
      run: gcc -std=c11 -O3 ${{ matrix.native && '-march=native' || '' }} -o example.exe example.c

    - name: Run example (Unix)
      if: runner.os != 'Windows'
      run: ./example

    - name: Run example (Windows)
      if: runner.os == 'Windows'
      run: .\example.exe
